name: hotelbooking
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  http: any
#  shared_preferences: any
  fluttertoast: ^8.1.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  shimmer: ^2.0.0
  transparent_image: ^2.0.0
  flutter_slidable: ^1.2.0
  # carousel_pro: ^1.0.0
  simple_animations: ^4.0.1
  like_button: ^2.0.4
  percent_indicator: ^4.0.0
  # flutter_rating: ^0.0.2
  # giffy_dialog: ^1.3.0
  flutter_credit_card: ^3.0.1
  google_maps_flutter: ^2.1.2
  country_icons: ^2.0.2
  firebase_auth: ^4.1.0
  firebase_messaging: ^14.0.3
  share:
  sqflite:
  image_picker: ^0.8.6
  cached_network_image: ^3.2.1
  get: ^4.6.5
  get_storage: ^2.0.3
  path_provider: 2.0.2
  dio: ^4.0.6
  http_parser:
  list_tile_switch:
  syncfusion_flutter_sliders:
  syncfusion_flutter_core:
  flutter_rating_bar:
  shared_preferences: ^2.0.15
  lottie: ^2.1.0
  url_launcher: ^6.1.7
  share_plus: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

#  flutter_native_splash: 2.2.0+1
#flutter_native_splash:
#  color: "#000000"
#  #  color: "#364c41"
#  image: "assets/image/images/logo.png"
#  # flutter pub run flutter_native_splash:create


  flutter_launcher_icons:
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/image/images/icon.png"
  # flutter pub run flutter_launcher_icons:main


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/map_style/
    - assets/image/onBoardingImage/
    - assets/image/splashScreen/
    - assets/image/icon/
    - assets/image/images/
    - assets/image/hotel/
    - assets/image/homeImage/
    - assets/image/destinationPopuler/
    - assets/image/illustration/
    - assets/image/room/
    - assets/image/destinationPopuler/
    - assets/image/profile/
    - assets/image/banner/
    - assets/image/logo/
    - assets/video/


  fonts:
    - family: Sans
      fonts:
        - asset: assets/font/OpenSans-Semibold.ttf
          weight: 600
        - asset: assets/font/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/font/OpenSans-Light.ttf
          weight: 200
    - family: One
      fonts:
        - asset: assets/font/HaveHeartOne.ttf
          weight: 400
    - family : Berlin
      fonts:
        - asset: assets/font/berlin.TTF
          weight: 600
    - family : Gotik
      fonts:
        - asset: assets/font/GOTHIC.TTF
          weight: 300
        - asset: assets/font/gotik.TTF
          weight: 600
    - family : Amira
      fonts:
        - asset: assets/font/Amira.otf
          weight: 500
    - family : Sofia
      fonts:
        - asset: assets/font/Sofia/SofiaProBold.otf
          weight: 900
        - asset: assets/font/Sofia/SofiaProSemiBold.otf
          weight: 800
        - asset: assets/font/Sofia/SofiaProMedium.otf
          weight: 700
        - asset: assets/font/Sofia/SofiaProRegular.otf
          weight: 600
        - asset: assets/font/Sofia/SofiaProLight.otf
          weight: 500
        - asset: assets/font/Sofia/SofiaProExtraLight.otf
          weight: 400
        - asset: assets/font/Sofia/SofiaProUltraLight.otf
          weight: 300
    - family : category
      fonts:
        - asset: assets/custom_icon/ic_category.ttf
    - family : message
      fonts:
        - asset: assets/custom_icon/ic_message.ttf
    - family : trip
      fonts:
        - asset: assets/custom_icon/ic_trip.ttf
    - family : file
      fonts:
        - asset: assets/custom_icon/ic_file.ttf
    - family : hearth
      fonts:
        - asset: assets/custom_icon/ic_hearth.ttf
    - family : home
      fonts:
        - asset: assets/custom_icon/ic_home.ttf
    - family : profile
      fonts:
        - asset: assets/custom_icon/ic_profile.ttf

# api_key_map: AIzaSyDMPcyBeJWPVoy7hPgJOBeiypmOWQtFiXc